### ISSUE TITLE
Remove gradient on tabs

### ISSUE THREAD

**Issue by Keith94** [alphapapa/fabtabs#3]
Hi, interesting add-on, but I would opt to remove the gradients (they don't look good on vertical tabs), is there a way to do it?

![firefox_2016-12-25_00-29-52](https://cloud.githubusercontent.com/assets/5490615/21470336/4a598518-ca39-11e6-8050-4f88d1e7cfc5.png)

**Comment by alphapapa** [comment]
Well, IIRC, you could change or remove them by editing the PNG files, or removing one of the overlays (remember I am not the original author of this extension, so I'm not an expert on its internals).  However, in that screenshot, it looks like removing the gradient would remove the visual distinction between the tabs that are the same color, so something else might need to be added to fix that.

**Comment by Keith94** [comment]
Okay, just found a way to remove it by editing `tabtint.js`; changing `50%` to `0%` does the trick.

https://github.com/alphapapa/tabtint/blob/master/chrome/content/tabtint/tabtint.js#L394

**Comment by alphapapa** [comment]
Ah, great, that was easy.  I guess that could be added as a setting someday, assuming this extension survives the great XUL-endectomy.  :(
